change-type:
    type: select
    destination: title
    after-string: '] '
    before-string: '['
    instructions: What kind of change?
    modifiable: true
    options:
        - fix
        - add
        - refactor
        - clean-up
commit-title:
    destination: title
    placeholder: Commit Title
    type: text
commit-description:
    allow-empty: true
    destination: body
    instructions: Please describe your changes.
    type: multiline-text
code-sections:
    type: multi-select
    record-as: joined-string
    allow-empty: true
    before-string: "\nCode Sections: "
    after-string: "\n"
    destination: body
    instructions: Which section(s) of the codebase?
    modifiable: true
    options:
        - tokendiff
        - fenestro
        - html
        - js
        - css
        - tests
        - configuration
        - ui
        - documentation
ticket-number:
    allow-empty: true
    before-string: "\n\nTicket: "
    data-type: integer
    destination: body
    instructions: Associated Ticket Number (if any)
    type: text
