#!/usr/bin/env sh
A=$1
B=$2

#echo "LOCAL: $A"
#echo "REMOTE: $B"
#echo "MERGED: $3" # unused

USE_FENESTRO=false
DELETE_TEMPFILES=true
BROWSER="" # "Firefox"
TEMP_FILE="$(mktemp /tmp/cleandifffapp.XXXXXX).cdiff"
HTML_EXTENSION=".html"
# make sure we're only dealing with text files
unset LANG
# if you don't unset LANG then some files will cause the file command
# to return: ERROR: line 22: regexec error 17, (illegal byte sequence)

if file $A | grep 'text' >/dev/null 2>&1 || \
	file $B | grep 'text' >/dev/null 2>&1 ; then

	# The heart of our functionality.
	# diff the files and have dwdiff break the results down into smaller "words"


	dwdiff --start-delete="<deleted>" \
		--stop-delete="</deleted>" \
		--start-insert="<inserted>" \
		--stop-insert="</inserted>" \
	    --delimiters="\x0A%,;/:._{}[]()'\!|-=~><\"\\\\" \
		--repeat-markers \
		-A best --repeat-markers -L $A $B | cat > $TEMP_FILE

	# Extract the name of the file we're diffing
	# $A and $B aren't trustable as names because
	# when used with git diff(tool) they'll just be temp files.
	# There are a couple lines which start with --- and +++
	# which mention the name of the "left" and "right" sides of the diff.
	# I've chosen the "right" one because it's more likely to be
	# what you ended up with.
	#FILE_NAME=`grep -m1 --color=none +++ $TEMP_FILE | sed -e 's/+++ //' -e 's/	.*//'`
	FILE_NAME=`basename $1 | sed -E 's|^.{6}_||'`
	FILE_NAME_2=`basename $2 | sed -E 's|^.{6}_||'`
	if [ "$FILE_NAME" != "$FILE_NAME_2" ]; then
		if [ "$FILE_NAME" != "null" ] && [ "$FILE_NAME_2" != "null" ]; then
			FILE_NAME="$FILE_NAME -> $FILE_NAME_2"
		elif [ "$FILE_NAME" == "null" ]; then
			FILE_NAME=$FILE_NAME_2
		# otherwise FILE_NAME is good to go
		fi
	fi

	# Clean up the dwdiff output.
	# * Remove the escape codes that shouldn't be there but are
	# * Remove the leading whitespace before the line numbers
	# * give the newline only inserted & deleted tags some content
	# *

	cat $TEMP_FILE \
		| gsed -E "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[m,K,H,f,J]//gm" \
		| gsed -E "s/\x1B\([A-Z]{1}(\x1B\[[m,K,H,f,J])?//gm" \
	 	| sed -E "s/("$'\E'"\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]) +([0-9]+)/\1\5/g" \
		| sed -E 's/^ +([0-9]+:[0-9]+) *(.*)/<diffline><linum>\1<\/linum><raw>\2 <\/raw><\/diffline>/' \
	    | sed -e "s/<inserted><\/inserted>/<inserted>⏎<\/inserted>/g" \
		-e "s/<deleted><\/deleted>/<deleted>⏎<\/deleted>/g" \
		| sed -E "/inserted|deleted/!s/<diffline>/<diffline class='unchanged'>/g" \
		> $TEMP_FILE$HTML_EXTENSION

	    # -e "s/<inserted>INSERTED<\/inserted>//g" \
		# -e "s/<deleted>DELETED<\/deleted>//g" \
		# > $TEMP_FILE$HTML_EXTENSION

# 	# Clean up the HTML
# 	# NOTE:
# 	#  The weird newlines in the middle of the sed substitutions are because
# 	#  it seems to be the best way to get a newline in there.. :/
# 	#
# 	# * build table cells and rows around line numbers, and comments.

# 	cat $TEMP_FILE$HTML_EXTENSION \
# 		| sed -e 's/<span class="bold green "><\/span>//g' \
# 		  -e 's/<span class="bold red "><\/span>//g' \
# 		| sed -E "s/^[[:space:]]+//g" \
# 		| sed -E "s|^([0-9]+:[0-9]+) {2,4}|</span></div>\
# <div class='line pre'><span class='linenums'><a class='linenum_link' name='\1'>\1</a></span><span class='source'>|" \
# 		| sed -E "s|^([0-9]+:[0-9]+) {0,4}|</span></div>\
# <div class='line pre'><span class='linenums'><a class='linenum_link' name='\1'>\1</a></span><span class='source'>|" \
# 		| sed -e $"s/<div class='line pre'>/\n\t\t\t<div class='line pre'>/g" \
# 		| sed -E -e '/class="bold red|class="bold green/! {s/line pre/line pre unchanged/g;}' \
# 		> "$TEMP_FILE.partial.$HTML_EXTENSION"


	# what's that you say?
	# symlinks suck in bash?
	# yes... yes they do.
	pushd `dirname $0` > /dev/null
	SCRIPT_PATH=`pwd -P`
	if [ -h "$SCRIPT_PATH/cdiff" ]; then # if it's a symbolic link
		SCRIPT_PATH=$(dirname $(readlink "$SCRIPT_PATH/cdiff" ))
		# set the path to the folder containing the file
		# the symlink points to
	fi
	# Haz ourselves some CSS
	# for prettification.
	CSS=$(cat "$SCRIPT_PATH/cleandiff.css")
	JS=$(cat "$SCRIPT_PATH/cleandiff.js")
	ICON=$(cat "$SCRIPT_PATH/visibility_icon.svg")

	# Haz ourselves some HTML
	# for browserfication.
	HEADER=$(cat <<EOL
	<html>
		<head>
			<title>$FILE_NAME</title>
			<style>
			$CSS
			</style>
			<script language="JavaScript">
				$JS
			</script>
		</head>
		<body>
			<input type="checkbox" id="unchanged_checkbox">
			<div class="filename">
				<label for="unchanged_checkbox">
            $ICON
			$FILE_NAME
				</label>
			</div>
			<diff>

EOL
		  )


	# Mas HTML por favor.
	FOOTER=$(cat <<EOL
			</diff>
		<script language="JavaScript">
			activateLineNumbers();
		</script>
		</body>
	</html>

EOL
		  )


	# you put your header in, you put your css in, you put your footer in
	# and you shake it all around.
	echo "$HEADER$(<"$TEMP_FILE$HTML_EXTENSION")$FOOTER" > $TEMP_FILE$HTML_EXTENSION

	# You do the hokey pokey, and you turn yourself around.
	# That's what it's all about.

	if [ -e "$HOME/.config/cdiff/cdiff1.sh" ]; then
		source "$HOME/.config/cdiff/cdiff1.sh"
	fi
	if [ "$USE_FENESTRO" == "true" ]; then
		fenestra --path=$TEMP_FILE$HTML_EXTENSION --name="$FILE_NAME"
	elif [ "$BROWSER" != "" ]; then
		open -a "$BROWSER" $TEMP_FILE$HTML_EXTENSION
	else
		open $TEMP_FILE$HTML_EXTENSION
	fi
	sleep 0.5
    if [ "$DELETE_TEMPFILES" == "true" ]; then
		rm "$TEMP_FILE"*
    else
      echo "tempfiles for $FILE_NAME"
      echo "run rm $TEMP_FILE* to delete these."
      ls "$TEMP_FILE"*
    fi
	exit 0
else
	if [ "/dev/null" == "$A" ]; then
		echo "Skipping binary file $B" # an added file
	else
		echo "Skipping binary file $A" # a removed file
	fi
	exit 1 # we don't diff binary files
fi
