#!/usr/bin/env sh
#echo "LOCAL: $1"
#echo "REMOTE: $2"
#echo "MERGED: $3"

TEMP_FILE="$(mktemp /tmp/cleandifffapp.XXXXXX).cdiff"
HTML_EXTENSION=".html"

diff -u $1 $2 | dwdiff -A best -L -c -d "\x0A%,;/:._{}[]()|-=~>\"\\\\" \
	--diff-input - | cat > $TEMP_FILE

FILE_PATH=`grep --color=none +++ $TEMP_FILE | sed -e 's/+++ //' -e 's/	.*//'`


cat $TEMP_FILE \
	| sed -e '/^\+\+\+/ d' -e '/^---/ d' -e '/^@@.*@@/d' \
	| sed -E 's/^ +([0-9]+:[0-9]+)/\1/' \
	| sed -E "s/("$'\E'"\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]) +([0-9]+)/\1\5/g" \
	| aha --stylesheet --no-header -t "$FILE_PATH" \
	> $TEMP_FILE$HTML_EXTENSION

cat $TEMP_FILE$HTML_EXTENSION \
	| sed -E "s|^([0-9]+:[0-9]+) {4}|</dd></div>\\\n<div class='line'><dt>\1</dt><dd class='pre'>|" \
	| sed -E "s|^</span>([0-9]+:[0-9]+) {0,4}|</span></dd></div>\\\n<div class='line'><dt>\1</dt><dd class='pre'>|" \
	> "$TEMP_FILE"

CSS=$(cat <<EOL
linenums{
	display: inline-block;
	min-width: 1%;
	padding-right: 0.25rem;
	border-right: solid 1px #ccc;
}
.pre {
	font-family: monospace;
	white-space: pre;
}
dt,dd{
	font-family: monospace;
	height: 1em;
	display: inline-block;
}
dl {
	position: relative;
}
.line{
	display:block;
}
.bold {font-style: bold;}
.green { color: green; }
.red { color: red;}

EOL)

HEADER=$(cat <<EOL
<html>
	<head>
		<title>$FILE_PATH</title>
		<style>
		$CSS
		</style>
	</head>
	<body>
		<dl>
			<dt style="display:none;"></dt><dd style="display:none;"><!-- temporary to compensate for 1st one -->
EOL)

FOOTER=$(cat <<EOL
</dl>
	</body>
</html>
EOL)

echo "$HEADER$(<$TEMP_FILE)$FOOTER" > $TEMP_FILE$HTML_EXTENSION


#gvim -O $TEMP_FILE
open -a Google\ Chrome $TEMP_FILE$HTML_EXTENSION
#open -a Safari $TEMP_FILE$HTML_EXTENSION
sleep 1
mv $TEMP_FILE$HTML_EXTENSION "foo.html"
#rm $TEMP_FILE $TEMP_FILE$HTML_EXTENSION
rm $TEMP_FILE

exit 0
