#!/usr/bin/env sh
#echo "LOCAL: $1"
#echo "REMOTE: $2"
#echo "MERGED: $3"

TEMP_FILE="$(mktemp /tmp/cleandifffapp.XXXXXX).cdiff"
HTML_EXTENSION=".html"

diff -u $1 $2 | dwdiff -A best -L -c -d "\x0A%,;/:._{}[]()'|-=~>\"\\\\" \
	--diff-input - | cat > $TEMP_FILE

FILE_PATH=`grep --color=none +++ $TEMP_FILE | sed -e 's/+++ //' -e 's/	.*//'`


cat $TEMP_FILE \
	| sed -e '/^\+\+\+/ d' -e '/^---/ d' -e '/^@@.*@@/d' \
	| sed -E 's/^ +([0-9]+:[0-9]+)/\1/' \
	| sed -E "s/("$'\E'"\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]) +([0-9]+)/\1\5/g" \
	| aha --stylesheet --no-header -t "$FILE_PATH" \
	> $TEMP_FILE$HTML_EXTENSION

cat $TEMP_FILE$HTML_EXTENSION \
	| sed -E "s|^([0-9]+:[0-9]+) {4}|</td></tr>\\\n<tr class='line pre' valign='top'><td class='linenums'>\1</td><td class='source'>|" \
	| sed -E "s|^</span>([0-9]+:[0-9]+) {0,4}|</span></td></tr>\\\n<tr class='line pre' valign='top'><td class='linenums'>\1</td><td class='source'>|" \
	> "$TEMP_FILE"

CSS=$(cat <<EOL
body{
	background: rgb(36,36,36);
	color: rgb(223, 216, 206);
}
.pre {
	font-family: monospace;
	white-space: pre;
}
tr {
	border: solid 1px black;
	margin: 0px;
}
td.linenums{
	margin-right: 1rem;
	padding-right: 0.5rem;
	border-right: solid 1px #ccc;
	text-align: right;
	color: rgb(255,222,165);
}
td.source{
	margin-left: 1rem;
	padding-left: 0.5rem;
}
.bold {font-style: bold;}
.green { color: #79DB73;}
.red { color: #af8dc3;}

EOL)

HEADER=$(cat <<EOL
<html>
	<head>
		<title>$FILE_PATH</title>
		<style>
		$CSS
		</style>
	</head>
	<body>
		<table cellpadding="0" cellspacing="0">
			<tr><td style="display:none;"></td><td style="display:none;"><!-- temporary to compensate for 1st one -->
EOL)

FOOTER=$(cat <<EOL
</table>
	</body>
</html>
EOL)

echo "$HEADER$(<$TEMP_FILE)$FOOTER" > $TEMP_FILE$HTML_EXTENSION


#gvim -O $TEMP_FILE
open -a Google\ Chrome $TEMP_FILE$HTML_EXTENSION
#open -a Safari $TEMP_FILE$HTML_EXTENSION
sleep 1
mv $TEMP_FILE$HTML_EXTENSION "foo.html"
#rm $TEMP_FILE $TEMP_FILE$HTML_EXTENSION
rm $TEMP_FILE

exit 0
